/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockFunctionsRouter,
  MockFunctionsRouterInterface,
} from "../../../contracts/mocks/MockFunctionsRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint64",
        name: "subscriptionId",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
      {
        internalType: "uint16",
        name: "dataVersion",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "donId",
        type: "bytes32",
      },
    ],
    name: "sendRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506101ad8061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c8063461d27621461002d575b5f80fd5b61004061003b3660046100ca565b610052565b60405190815260200160405180910390f35b5f80428860405160200161007d92919091825260c01b6001600160c01b031916602082015260280190565b60408051808303601f19018152919052805160209091012098975050505050505050565b803561ffff811681146100b2575f80fd5b919050565b803563ffffffff811681146100b2575f80fd5b5f805f805f8060a087890312156100df575f80fd5b863567ffffffffffffffff80821682146100f7575f80fd5b9096506020880135908082111561010c575f80fd5b818901915089601f83011261011f575f80fd5b81358181111561012d575f80fd5b8a602082850101111561013e575f80fd5b602083019750809650505050610156604088016100a1565b9250610164606088016100b7565b915060808701359050929550929550929556fea264697066735822122081d11a48b09059573dd98a1ed4b51f24ba36ddc301244dd59c95365a82bfa67d64736f6c63430008180033";

type MockFunctionsRouterConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockFunctionsRouterConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockFunctionsRouter__factory extends ContractFactory {
  constructor(...args: MockFunctionsRouterConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockFunctionsRouter & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockFunctionsRouter__factory {
    return super.connect(runner) as MockFunctionsRouter__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockFunctionsRouterInterface {
    return new Interface(_abi) as MockFunctionsRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockFunctionsRouter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockFunctionsRouter;
  }
}
