/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIcmMessenger,
  IIcmMessengerInterface,
} from "../../../contracts/interfaces/IIcmMessenger";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "sourceBlockchainID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sourceAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "InterchainMessageReceived",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "destinationBlockchainID",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "destinationAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "InterchainMessageSent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "sourceBlockchainID",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "sourceAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "receiveInterchainMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "destinationBlockchainID",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "destinationAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "sendInterchainMessage",
    outputs: [
      {
        internalType: "uint256",
        name: "messageNonce",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IIcmMessenger__factory {
  static readonly abi = _abi;
  static createInterface(): IIcmMessengerInterface {
    return new Interface(_abi) as IIcmMessengerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIcmMessenger {
    return new Contract(address, _abi, runner) as unknown as IIcmMessenger;
  }
}
