/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { BitacoraInmueble__factory } from "./BitacoraInmueble__factory";
export { FibraManager__factory } from "./FibraManager__factory";
export { LadrilloBrick__factory } from "./LadrilloBrick__factory";
