/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IPropertyStructures {
  export type PropertyRecordStruct = {
    currentOwner: AddressLike;
    constructionDate: BigNumberish;
    status: BigNumberish;
    isLocked: boolean;
    area: BigNumberish;
    brickTokenAddress: AddressLike;
    cadastralKey: string;
    ipfsMetadataHash: string;
  };

  export type PropertyRecordStructOutput = [
    currentOwner: string,
    constructionDate: bigint,
    status: bigint,
    isLocked: boolean,
    area: bigint,
    brickTokenAddress: string,
    cadastralKey: string,
    ipfsMetadataHash: string
  ] & {
    currentOwner: string;
    constructionDate: bigint;
    status: bigint;
    isLocked: boolean;
    area: bigint;
    brickTokenAddress: string;
    cadastralKey: string;
    ipfsMetadataHash: string;
  };
}

export interface IBitacoraInmuebleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "externalLogHistory"
      | "ownerOf"
      | "properties"
      | "safeTransferFrom"
      | "setPropertyLock"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "externalLogHistory",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPropertyLock",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "externalLogHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPropertyLock",
    data: BytesLike
  ): Result;
}

export interface IBitacoraInmueble extends BaseContract {
  connect(runner?: ContractRunner | null): IBitacoraInmueble;
  waitForDeployment(): Promise<this>;

  interface: IBitacoraInmuebleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  externalLogHistory: TypedContractMethod<
    [propertyId: BigNumberish, description: string],
    [void],
    "nonpayable"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  properties: TypedContractMethod<
    [propertyId: BigNumberish],
    [IPropertyStructures.PropertyRecordStructOutput],
    "view"
  >;

  safeTransferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPropertyLock: TypedContractMethod<
    [propertyId: BigNumberish, lockState: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "externalLogHistory"
  ): TypedContractMethod<
    [propertyId: BigNumberish, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [propertyId: BigNumberish],
    [IPropertyStructures.PropertyRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPropertyLock"
  ): TypedContractMethod<
    [propertyId: BigNumberish, lockState: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
