/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBitacoraInmueble } from "./IBitacoraInmueble";
export type { PropertyEscrow } from "./PropertyEscrow";
