/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PropertyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COMMISSION_BPS"
      | "REQUEST_TIMEOUT"
      | "bitacora"
      | "cancelarPeticionExpirada"
      | "deals"
      | "decodeAndApply"
      | "depositarFondos"
      | "donId"
      | "handleOracleFulfillment"
      | "iniciarContrato"
      | "liquidarTransaccion"
      | "marketplaceWallet"
      | "pendingRequests"
      | "reclamarReembolso"
      | "solicitarAuditoriaDeAdeudos"
      | "subscriptionId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditFailed"
      | "AuditRequested"
      | "ConditionsVerified"
      | "DealLiquidated"
      | "EscrowStatusChanged"
      | "FundsDeposited"
      | "FundsRefunded"
      | "RequestExpired"
      | "RequestFulfilled"
      | "RequestSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COMMISSION_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REQUEST_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bitacora", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelarPeticionExpirada",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "deals", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "decodeAndApply",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositarFondos",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "donId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "handleOracleFulfillment",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "iniciarContrato",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidarTransaccion",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplaceWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reclamarReembolso",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "solicitarAuditoriaDeAdeudos",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COMMISSION_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REQUEST_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bitacora", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelarPeticionExpirada",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decodeAndApply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositarFondos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "handleOracleFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "iniciarContrato",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidarTransaccion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplaceWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reclamarReembolso",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "solicitarAuditoriaDeAdeudos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionId",
    data: BytesLike
  ): Result;
}

export namespace AuditFailedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    propertyId: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    requestId: string,
    propertyId: bigint,
    reason: string
  ];
  export interface OutputObject {
    requestId: string;
    propertyId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditRequestedEvent {
  export type InputTuple = [requestId: BytesLike, propertyId: BigNumberish];
  export type OutputTuple = [requestId: string, propertyId: bigint];
  export interface OutputObject {
    requestId: string;
    propertyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConditionsVerifiedEvent {
  export type InputTuple = [propertyId: BigNumberish, isClear: boolean];
  export type OutputTuple = [propertyId: bigint, isClear: boolean];
  export interface OutputObject {
    propertyId: bigint;
    isClear: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealLiquidatedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    sellerAmount: BigNumberish,
    commission: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: bigint,
    sellerAmount: bigint,
    commission: bigint
  ];
  export interface OutputObject {
    propertyId: bigint;
    sellerAmount: bigint;
    commission: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowStatusChangedEvent {
  export type InputTuple = [propertyId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [propertyId: bigint, newStatus: bigint];
  export interface OutputObject {
    propertyId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [propertyId: bigint, buyer: string, amount: bigint];
  export interface OutputObject {
    propertyId: bigint;
    buyer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsRefundedEvent {
  export type InputTuple = [propertyId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [propertyId: bigint, buyer: string];
  export interface OutputObject {
    propertyId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestExpiredEvent {
  export type InputTuple = [requestId: BytesLike, propertyId: BigNumberish];
  export type OutputTuple = [requestId: string, propertyId: bigint];
  export interface OutputObject {
    requestId: string;
    propertyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFulfilledEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSentEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PropertyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): PropertyEscrow;
  waitForDeployment(): Promise<this>;

  interface: PropertyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COMMISSION_BPS: TypedContractMethod<[], [bigint], "view">;

  REQUEST_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  bitacora: TypedContractMethod<[], [string], "view">;

  cancelarPeticionExpirada: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  deals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        propertyId: bigint;
        price: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  decodeAndApply: TypedContractMethod<
    [propertyId: BigNumberish, response: BytesLike],
    [void],
    "nonpayable"
  >;

  depositarFondos: TypedContractMethod<
    [propertyId: BigNumberish],
    [void],
    "payable"
  >;

  donId: TypedContractMethod<[], [string], "view">;

  handleOracleFulfillment: TypedContractMethod<
    [requestId: BytesLike, response: BytesLike, err: BytesLike],
    [void],
    "nonpayable"
  >;

  iniciarContrato: TypedContractMethod<
    [
      propertyId: BigNumberish,
      buyer: AddressLike,
      price: BigNumberish,
      duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  liquidarTransaccion: TypedContractMethod<
    [propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  marketplaceWallet: TypedContractMethod<[], [string], "view">;

  pendingRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, boolean] & {
        propertyId: bigint;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;

  reclamarReembolso: TypedContractMethod<
    [propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  solicitarAuditoriaDeAdeudos: TypedContractMethod<
    [propertyId: BigNumberish, source: string],
    [string],
    "nonpayable"
  >;

  subscriptionId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COMMISSION_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REQUEST_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bitacora"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelarPeticionExpirada"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        propertyId: bigint;
        price: bigint;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decodeAndApply"
  ): TypedContractMethod<
    [propertyId: BigNumberish, response: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositarFondos"
  ): TypedContractMethod<[propertyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "donId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleOracleFulfillment"
  ): TypedContractMethod<
    [requestId: BytesLike, response: BytesLike, err: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "iniciarContrato"
  ): TypedContractMethod<
    [
      propertyId: BigNumberish,
      buyer: AddressLike,
      price: BigNumberish,
      duration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidarTransaccion"
  ): TypedContractMethod<[propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "marketplaceWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, boolean] & {
        propertyId: bigint;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reclamarReembolso"
  ): TypedContractMethod<[propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "solicitarAuditoriaDeAdeudos"
  ): TypedContractMethod<
    [propertyId: BigNumberish, source: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscriptionId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AuditFailed"
  ): TypedContractEvent<
    AuditFailedEvent.InputTuple,
    AuditFailedEvent.OutputTuple,
    AuditFailedEvent.OutputObject
  >;
  getEvent(
    key: "AuditRequested"
  ): TypedContractEvent<
    AuditRequestedEvent.InputTuple,
    AuditRequestedEvent.OutputTuple,
    AuditRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ConditionsVerified"
  ): TypedContractEvent<
    ConditionsVerifiedEvent.InputTuple,
    ConditionsVerifiedEvent.OutputTuple,
    ConditionsVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "DealLiquidated"
  ): TypedContractEvent<
    DealLiquidatedEvent.InputTuple,
    DealLiquidatedEvent.OutputTuple,
    DealLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowStatusChanged"
  ): TypedContractEvent<
    EscrowStatusChangedEvent.InputTuple,
    EscrowStatusChangedEvent.OutputTuple,
    EscrowStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "FundsRefunded"
  ): TypedContractEvent<
    FundsRefundedEvent.InputTuple,
    FundsRefundedEvent.OutputTuple,
    FundsRefundedEvent.OutputObject
  >;
  getEvent(
    key: "RequestExpired"
  ): TypedContractEvent<
    RequestExpiredEvent.InputTuple,
    RequestExpiredEvent.OutputTuple,
    RequestExpiredEvent.OutputObject
  >;
  getEvent(
    key: "RequestFulfilled"
  ): TypedContractEvent<
    RequestFulfilledEvent.InputTuple,
    RequestFulfilledEvent.OutputTuple,
    RequestFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "RequestSent"
  ): TypedContractEvent<
    RequestSentEvent.InputTuple,
    RequestSentEvent.OutputTuple,
    RequestSentEvent.OutputObject
  >;

  filters: {
    "AuditFailed(bytes32,uint256,bytes)": TypedContractEvent<
      AuditFailedEvent.InputTuple,
      AuditFailedEvent.OutputTuple,
      AuditFailedEvent.OutputObject
    >;
    AuditFailed: TypedContractEvent<
      AuditFailedEvent.InputTuple,
      AuditFailedEvent.OutputTuple,
      AuditFailedEvent.OutputObject
    >;

    "AuditRequested(bytes32,uint256)": TypedContractEvent<
      AuditRequestedEvent.InputTuple,
      AuditRequestedEvent.OutputTuple,
      AuditRequestedEvent.OutputObject
    >;
    AuditRequested: TypedContractEvent<
      AuditRequestedEvent.InputTuple,
      AuditRequestedEvent.OutputTuple,
      AuditRequestedEvent.OutputObject
    >;

    "ConditionsVerified(uint256,bool)": TypedContractEvent<
      ConditionsVerifiedEvent.InputTuple,
      ConditionsVerifiedEvent.OutputTuple,
      ConditionsVerifiedEvent.OutputObject
    >;
    ConditionsVerified: TypedContractEvent<
      ConditionsVerifiedEvent.InputTuple,
      ConditionsVerifiedEvent.OutputTuple,
      ConditionsVerifiedEvent.OutputObject
    >;

    "DealLiquidated(uint256,uint256,uint256)": TypedContractEvent<
      DealLiquidatedEvent.InputTuple,
      DealLiquidatedEvent.OutputTuple,
      DealLiquidatedEvent.OutputObject
    >;
    DealLiquidated: TypedContractEvent<
      DealLiquidatedEvent.InputTuple,
      DealLiquidatedEvent.OutputTuple,
      DealLiquidatedEvent.OutputObject
    >;

    "EscrowStatusChanged(uint256,uint8)": TypedContractEvent<
      EscrowStatusChangedEvent.InputTuple,
      EscrowStatusChangedEvent.OutputTuple,
      EscrowStatusChangedEvent.OutputObject
    >;
    EscrowStatusChanged: TypedContractEvent<
      EscrowStatusChangedEvent.InputTuple,
      EscrowStatusChangedEvent.OutputTuple,
      EscrowStatusChangedEvent.OutputObject
    >;

    "FundsDeposited(uint256,address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "FundsRefunded(uint256,address)": TypedContractEvent<
      FundsRefundedEvent.InputTuple,
      FundsRefundedEvent.OutputTuple,
      FundsRefundedEvent.OutputObject
    >;
    FundsRefunded: TypedContractEvent<
      FundsRefundedEvent.InputTuple,
      FundsRefundedEvent.OutputTuple,
      FundsRefundedEvent.OutputObject
    >;

    "RequestExpired(bytes32,uint256)": TypedContractEvent<
      RequestExpiredEvent.InputTuple,
      RequestExpiredEvent.OutputTuple,
      RequestExpiredEvent.OutputObject
    >;
    RequestExpired: TypedContractEvent<
      RequestExpiredEvent.InputTuple,
      RequestExpiredEvent.OutputTuple,
      RequestExpiredEvent.OutputObject
    >;

    "RequestFulfilled(bytes32)": TypedContractEvent<
      RequestFulfilledEvent.InputTuple,
      RequestFulfilledEvent.OutputTuple,
      RequestFulfilledEvent.OutputObject
    >;
    RequestFulfilled: TypedContractEvent<
      RequestFulfilledEvent.InputTuple,
      RequestFulfilledEvent.OutputTuple,
      RequestFulfilledEvent.OutputObject
    >;

    "RequestSent(bytes32)": TypedContractEvent<
      RequestSentEvent.InputTuple,
      RequestSentEvent.OutputTuple,
      RequestSentEvent.OutputObject
    >;
    RequestSent: TypedContractEvent<
      RequestSentEvent.InputTuple,
      RequestSentEvent.OutputTuple,
      RequestSentEvent.OutputObject
    >;
  };
}
