/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IcmReceiverFujiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedPortal"
      | "receivePropertyUpdate"
      | "remoteProperties"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PropertySynced"): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedPortal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receivePropertyUpdate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remoteProperties",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedPortal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receivePropertyUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remoteProperties",
    data: BytesLike
  ): Result;
}

export namespace PropertySyncedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    owner: AddressLike,
    status: BigNumberish
  ];
  export type OutputTuple = [propertyId: bigint, owner: string, status: bigint];
  export interface OutputObject {
    propertyId: bigint;
    owner: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IcmReceiverFuji extends BaseContract {
  connect(runner?: ContractRunner | null): IcmReceiverFuji;
  waitForDeployment(): Promise<this>;

  interface: IcmReceiverFujiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedPortal: TypedContractMethod<[], [string], "view">;

  receivePropertyUpdate: TypedContractMethod<
    [payload: BytesLike],
    [void],
    "nonpayable"
  >;

  remoteProperties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        status: bigint;
        lastSync: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedPortal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receivePropertyUpdate"
  ): TypedContractMethod<[payload: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "remoteProperties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        status: bigint;
        lastSync: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "PropertySynced"
  ): TypedContractEvent<
    PropertySyncedEvent.InputTuple,
    PropertySyncedEvent.OutputTuple,
    PropertySyncedEvent.OutputObject
  >;

  filters: {
    "PropertySynced(uint256,address,uint8)": TypedContractEvent<
      PropertySyncedEvent.InputTuple,
      PropertySyncedEvent.OutputTuple,
      PropertySyncedEvent.OutputObject
    >;
    PropertySynced: TypedContractEvent<
      PropertySyncedEvent.InputTuple,
      PropertySyncedEvent.OutputTuple,
      PropertySyncedEvent.OutputObject
    >;
  };
}
