/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as propertyEscrowSol from "./PropertyEscrow.sol";
export type { propertyEscrowSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
export type { BitacoraInmueble } from "./BitacoraInmueble";
export type { FibraManager } from "./FibraManager";
export type { IcmPropertyPortal } from "./IcmPropertyPortal";
export type { IcmReceiverFuji } from "./IcmReceiverFuji";
export type { LadrilloBrick } from "./LadrilloBrick";
