/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockIcmMessengerInterface extends Interface {
  getFunction(
    nameOrSignature: "receiveInterchainMessage" | "sendInterchainMessage"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "InterchainMessageReceived"
      | "InterchainMessageSent"
      | "MockMessageSent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "receiveInterchainMessage",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendInterchainMessage",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveInterchainMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendInterchainMessage",
    data: BytesLike
  ): Result;
}

export namespace InterchainMessageReceivedEvent {
  export type InputTuple = [
    sourceBlockchainID: BytesLike,
    sourceAddress: AddressLike,
    message: BytesLike
  ];
  export type OutputTuple = [
    sourceBlockchainID: string,
    sourceAddress: string,
    message: string
  ];
  export interface OutputObject {
    sourceBlockchainID: string;
    sourceAddress: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InterchainMessageSentEvent {
  export type InputTuple = [
    destinationBlockchainID: BytesLike,
    destinationAddress: AddressLike,
    nonce: BigNumberish,
    message: BytesLike
  ];
  export type OutputTuple = [
    destinationBlockchainID: string,
    destinationAddress: string,
    nonce: bigint,
    message: string
  ];
  export interface OutputObject {
    destinationBlockchainID: string;
    destinationAddress: string;
    nonce: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockMessageSentEvent {
  export type InputTuple = [
    destinationChainId: BytesLike,
    destinationAddress: AddressLike,
    payload: BytesLike
  ];
  export type OutputTuple = [
    destinationChainId: string,
    destinationAddress: string,
    payload: string
  ];
  export interface OutputObject {
    destinationChainId: string;
    destinationAddress: string;
    payload: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockIcmMessenger extends BaseContract {
  connect(runner?: ContractRunner | null): MockIcmMessenger;
  waitForDeployment(): Promise<this>;

  interface: MockIcmMessengerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receiveInterchainMessage: TypedContractMethod<
    [
      sourceBlockchainID: BytesLike,
      sourceAddress: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  sendInterchainMessage: TypedContractMethod<
    [
      destinationBlockchainID: BytesLike,
      destinationAddress: AddressLike,
      message: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receiveInterchainMessage"
  ): TypedContractMethod<
    [
      sourceBlockchainID: BytesLike,
      sourceAddress: AddressLike,
      message: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendInterchainMessage"
  ): TypedContractMethod<
    [
      destinationBlockchainID: BytesLike,
      destinationAddress: AddressLike,
      message: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "InterchainMessageReceived"
  ): TypedContractEvent<
    InterchainMessageReceivedEvent.InputTuple,
    InterchainMessageReceivedEvent.OutputTuple,
    InterchainMessageReceivedEvent.OutputObject
  >;
  getEvent(
    key: "InterchainMessageSent"
  ): TypedContractEvent<
    InterchainMessageSentEvent.InputTuple,
    InterchainMessageSentEvent.OutputTuple,
    InterchainMessageSentEvent.OutputObject
  >;
  getEvent(
    key: "MockMessageSent"
  ): TypedContractEvent<
    MockMessageSentEvent.InputTuple,
    MockMessageSentEvent.OutputTuple,
    MockMessageSentEvent.OutputObject
  >;

  filters: {
    "InterchainMessageReceived(bytes32,address,bytes)": TypedContractEvent<
      InterchainMessageReceivedEvent.InputTuple,
      InterchainMessageReceivedEvent.OutputTuple,
      InterchainMessageReceivedEvent.OutputObject
    >;
    InterchainMessageReceived: TypedContractEvent<
      InterchainMessageReceivedEvent.InputTuple,
      InterchainMessageReceivedEvent.OutputTuple,
      InterchainMessageReceivedEvent.OutputObject
    >;

    "InterchainMessageSent(bytes32,address,uint256,bytes)": TypedContractEvent<
      InterchainMessageSentEvent.InputTuple,
      InterchainMessageSentEvent.OutputTuple,
      InterchainMessageSentEvent.OutputObject
    >;
    InterchainMessageSent: TypedContractEvent<
      InterchainMessageSentEvent.InputTuple,
      InterchainMessageSentEvent.OutputTuple,
      InterchainMessageSentEvent.OutputObject
    >;

    "MockMessageSent(bytes32,address,bytes)": TypedContractEvent<
      MockMessageSentEvent.InputTuple,
      MockMessageSentEvent.OutputTuple,
      MockMessageSentEvent.OutputObject
    >;
    MockMessageSent: TypedContractEvent<
      MockMessageSentEvent.InputTuple,
      MockMessageSentEvent.OutputTuple,
      MockMessageSentEvent.OutputObject
    >;
  };
}
