/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBitacoraInmueble,
  IBitacoraInmuebleInterface,
} from "../../../contracts/PropertyEscrow.sol/IBitacoraInmueble";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "propertyId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "description",
        type: "string",
      },
    ],
    name: "externalLogHistory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "propertyId",
        type: "uint256",
      },
    ],
    name: "properties",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "currentOwner",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "constructionDate",
            type: "uint64",
          },
          {
            internalType: "enum IPropertyStructures.PropertyStatus",
            name: "status",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "isLocked",
            type: "bool",
          },
          {
            internalType: "uint32",
            name: "area",
            type: "uint32",
          },
          {
            internalType: "address",
            name: "brickTokenAddress",
            type: "address",
          },
          {
            internalType: "string",
            name: "cadastralKey",
            type: "string",
          },
          {
            internalType: "string",
            name: "ipfsMetadataHash",
            type: "string",
          },
        ],
        internalType: "struct IPropertyStructures.PropertyRecord",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "propertyId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "lockState",
        type: "bool",
      },
    ],
    name: "setPropertyLock",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBitacoraInmueble__factory {
  static readonly abi = _abi;
  static createInterface(): IBitacoraInmuebleInterface {
    return new Interface(_abi) as IBitacoraInmuebleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBitacoraInmueble {
    return new Contract(address, _abi, runner) as unknown as IBitacoraInmueble;
  }
}
