/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBitacoraInmueble__factory } from "./IBitacoraInmueble__factory";
export { PropertyEscrow__factory } from "./PropertyEscrow__factory";
